### ISSUE TITLE
ITS NOT OVER UNTIL I WIN

### ISSUE THREAD

**Issue by LumieOwO** [VictorRutskin/VictorRutskin#1]
Nobody believes in you
You've lost again and again
The lights are cut off
But you're still looking at your dream
Reviewing it every day and saying to yourself
It's not over until I win [x3]

**Comment by VictorRutskin** [comment]
ok buddy

**Comment by LumieOwO** [comment]
> Nobody believes in you
> You've lost again and again
> The lights are cut off
> But you're still looking at your dream
> Reviewing it every day and saying to yourself
> It'

this is a motivational thing
